# Generated by Django 6.0.5 on 2026-05-14 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models



def assign_user_default_owner(schema_editor):
    Note = apps.get_model("notes", "Note")
    User = apps.get_model("accounts", "User")


    user = User.objects.first()
    
    Note.objects.filter(owner__is_null=True).update(owner=user)


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='owner',
            field=models.ForeignKey(blank=None, on_delete=django.db.models.deletion.CASCADE, related_name='owners', to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=False,
        ),

        migrations.RunPython(assign_user_default_owner, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="note",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),

    ]
