# Generated by Django 6.0.5 on 2026-05-20 17:13

import copy
from django.db import migrations


def force_owner_not_null(apps, schema_editor):
    Note = apps.get_model("notes", "Note")

    if Note.objects.filter(owner__isnull=True).exists():
        raise RuntimeError("Cannot make notes.Note.owner non-null while NULL values exist.")

    old_field = copy.deepcopy(Note._meta.get_field("owner"))
    new_field = copy.deepcopy(Note._meta.get_field("owner"))

    old_field.model = Note
    new_field.model = Note
    old_field.null = True
    new_field.null = False

    schema_editor.alter_field(Note, old_field, new_field, strict=True)


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_note_owner'),
    ]

    operations = [
        migrations.RunPython(force_owner_not_null, migrations.RunPython.noop),
    ]
