# Generated by Django 6.0.5 on 2026-05-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_note_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tag',
            field=models.CharField(choices=[('STUDY', 'Study'), ('PERSONAL', 'Personal'), ('WORK', 'Work')], default='STUDY', max_length=20),
            preserve_default=False,
        ),
    ]
